/**
 * Canonical error codes for the Huddly Realtime Protocol (spec §7).
 */
export const ERROR_CODES = {
  // Authentication & Authorization (AUTH_*)
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_GUEST_RESTRICTED: 'AUTH_GUEST_RESTRICTED',

  // Room Domain (ROOM_*)
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_FULL: 'ROOM_FULL',
  ROOM_LOCKED: 'ROOM_LOCKED',
  ROOM_CLOSED: 'ROOM_CLOSED',
  ROOM_INVITE_INVALID: 'ROOM_INVITE_INVALID',
  ROOM_INVITE_EXPIRED: 'ROOM_INVITE_EXPIRED',
  ROOM_MEMBER_NOT_FOUND: 'ROOM_MEMBER_NOT_FOUND',
  ROOM_ROLE_INSUFFICIENT: 'ROOM_ROLE_INSUFFICIENT',

  // Playback & Sync Domain (SYNC_*)
  SYNC_INVALID_REVISION: 'SYNC_INVALID_REVISION',
  SYNC_STALE_EVENT: 'SYNC_STALE_EVENT',
  SYNC_MEDIA_MISMATCH: 'SYNC_MEDIA_MISMATCH',
  SYNC_RATE_UNSUPPORTED: 'SYNC_RATE_UNSUPPORTED',
  SYNC_DRIFT_EXCEEDED: 'SYNC_DRIFT_EXCEEDED',
  SYNC_SEEK_OUT_OF_BOUNDS: 'SYNC_SEEK_OUT_OF_BOUNDS',

  // WebRTC & Media Domain (WEBRTC_*)
  WEBRTC_TOKEN_FAILED: 'WEBRTC_TOKEN_FAILED',
  WEBRTC_ROOM_DISCONNECTED: 'WEBRTC_ROOM_DISCONNECTED',
  WEBRTC_PEER_FAILED: 'WEBRTC_PEER_FAILED',
  WEBRTC_TRACK_SUBSCRIPTION_FAILED: 'WEBRTC_TRACK_SUBSCRIPTION_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
